stages:
  - check
  - deploy

variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive

include:
  - local: "tests/ci/check.gitlab-ci.yaml"

pages:
  stage: deploy
  image: python:3.9-alpine
  script:
    - apk add git
    - pip install -U GitPython
    - pip install -U sphinx
    - pip install -U sphinx-rtd-theme
    - pip install -U sphinx-vhdl
    - echo "Hotfix detached head, causing trouble in GitPython:"
    - git checkout $CI_COMMIT_BRANCH
    - git status
    - sphinx-build -b html doc/source/ public
  artifacts:
    paths:
      - public
  only:
    - devel
