# Makefile: Makefile to compile module
# Copyright (C) 2025 CESNET z.s.p.o.
# Author(s): Jakub Cabal <cabal@cesnet.cz>
#
# SPDX-License-Identifier: BSD-3-Clause

TOP_LEVEL_ENT=TSU_ASYNC

all: comp
include ../../../../build/Makefile
.PHONY: all
